### ISSUE TITLE
[Converter - Local] "AttributeError: 'NoneType' object has no attribute 'issue_path'"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1508]
Verifiquei que o arquivo 1678-9199-jvatitd-s40409-015-0008-9 apresenta erro ao converter pelo local. Veja o erro:
```code
1678-9199-jvatitd-s40409-015-0008-9
-----------------------------------
 ... created
debug: find_i_record
['2015nahead', '1678-9199', None]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1410, in __call__
    return self.func(*args)
  File "C:\Markup_89\bin\xml\modules\xml_gui.py", line 137, in run_xml_converter

    xml_converter(self.selected_folder, self.collection_name)
  File "C:\Markup_89\bin\xml\modules\xml_gui.py", line 165, in xml_converter
    xmlcvrter.execute_converter(path, COLLECTIONS.get(collection_name))
  File "C:\Markup_89\bin\xml\modules\xmlcvrter.py", line 871, in execute_convert
er
    report_location, scilista_item, acron_issue_label, results = convert_package
(package_path)
  File "C:\Markup_89\bin\xml\modules\xmlcvrter.py", line 371, in convert_package

    texts.append(pkg_reports.processing_result_location(issue_files.issue_path))
AttributeError: 'NoneType' object has no attribute 'issue_path'.
```

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1508

**MODULO - XMLConverter
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
duplicated #1491
