### ISSUE TITLE
[Relatórios - XPM | XC] - Travam ao validar um pacote

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1643]
Verificamos que os validadores "XPM" e "XC" param ao validar pacotes xml.
Veja a mensagem apresentada:

**XC:**
```code
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1410, in __call__
    return self.func(*args)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xml_gui.py", line 134, in ru
n_xml_converter
    xml_converter(self.selected_folder)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xml_gui.py", line 171, in xm
l_converter
    xmlcvrter.execute_converter(path)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xmlcvrter.py", line 1058, in
 execute_converter
    prepare_env(config)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xmlcvrter.py", line 1129, in
 prepare_env
    update_db_copy(config.title_db, config.title_db_copy, CURRENT_PATH + '/title
.fst')
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xmlcvrter.py", line 1008, in
 update_db_copy
    shutil.copyfile(fst_file, isis_db_copy + '.fst')
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'C:/markup90trial2new/SciELO/bin/x
ml/modules/title.fst'
```
**Obs.:** o erro foi apresentado mesmo copiando a title e issue para o serial do PC-Programs

**XPM:**
```code
11/12: 1984-0292-fractal-27-2-0165
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1410, in __call__
    return self.func(*args)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xml_gui.py", line 122, in ru
n_xml_package_maker
    xml_package_maker(self.selected_folder, self.acron)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xml_gui.py", line 159, in xm
l_package_maker
    xpmaker.make_packages(path, acron)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xpmaker.py", line 1032, in m
ake_packages
    pack_and_validate(xml_files, results_path, acron, version)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\xpmaker.py", line 886, in pa
ck_and_validate
    report_components['detail-report'] = articles_pkg_reports.detail_report()
  File "C:\markup90trial2new\SciELO\bin\xml\modules\pkg_reports.py", line 486, i
n detail_report
    content = get_report_text(rep)
  File "C:\markup90trial2new\SciELO\bin\xml\modules\pkg_reports.py", line 589, i
n get_report_text
    content = content.decode('utf-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfa in position 2871: invali
d start byte
```

**XPM - Instalado à parte:**

```code
5/13: 1516-8484-rbhh-37-03-00167
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1410, in __call__
    return self.func(*args)
  File "C:\xpm4.0.090\scielo-xpm\xml\modules\xml_gui.py", line 122, in run_xml_p
ackage_maker
    xml_package_maker(self.selected_folder, self.acron)
  File "C:\xpm4.0.090\scielo-xpm\xml\modules\xml_gui.py", line 159, in xml_packa
ge_maker
    xpmaker.make_packages(path, acron)
  File "C:\xpm4.0.090\scielo-xpm\xml\modules\xpmaker.py", line 1032, in make_pac
kages
    pack_and_validate(xml_files, results_path, acron, version)
  File "C:\xpm4.0.090\scielo-xpm\xml\modules\xpmaker.py", line 886, in pack_and_
validate
    report_components['detail-report'] = articles_pkg_reports.detail_report()
  File "C:\xpm4.0.090\scielo-xpm\xml\modules\pkg_reports.py", line 486, in detai
l_report
    content = get_report_text(rep)
  File "C:\xpm4.0.090\scielo-xpm\xml\modules\pkg_reports.py", line 589, in get_r
eport_text
    content = content.decode('utf-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfa in position 1397: invali
d start byte
```

Notei que a pasta com o relatório de erros é criada e os arquivos .html de cada arquivo também, porém o relatório .html que compacta todos os relatórios em um único não é gerado.

**Comment by robertatakenaka** [comment]
O pacote ou algum arquivo possui no nome caracteres acentuados?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by leticiaquino** [comment]
@robertatakenaka não há acentos no pacote, nem no arquivo.

**Comment by robertatakenaka** [comment]
O pacote foi enviado para mim?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by leticiaquino** [comment]
@robertatakenaka Esse não, mas envio agora por e-mail.

**Comment by robertatakenaka** [comment]
@leticiaquino : não consigo reproduzir o erro. Acontece com qualquer pacote? Você mais de uma versão de python 2.7.x na sua máquina? Tente eliminar, deixar apenas 1 versão 2.7.

**Comment by leticiaquino** [comment]
@robertatakenaka isso ocorre para qualquer pacote e qualquer versão do Markup que eu utilizo. O estranho é que semana retrasada estava funcionando corretamente, na verdade sempre funcionou.

Pedi agora para que a Luana testasse na máquina dela e o resultado foi o mesmo.
Obs.: A Luana tem apenas o Python 2.7 na máquina.
