### ISSUE TITLE
[xpm] Não gera arquivos PMC quando pasta tem acentuação

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2241]
O XPM não finaliza a geração dos arquivos PMC, na pasta pmc_package, quando os arquivos estão inseridos em uma pasta que contém acentuação. Exemplo:

C:\Users\luana.araujo\Desktop\**verificação PMC**\rimtsp\lote 04

Gerou ao retirar acentuação:
C:\Users\luana.araujo\Desktop\**verificacao PMC**\rimtsp\lote 04

**Comment by robertatakenaka** [comment]
fechado por engano

**Comment by leticiaquino** [comment]
@robertatakenaka o problema apontado continua.
Validei uma pasta com a nomeação "Testão-xpm" e o programa não gerou o pacote PMC. Além disso, é apresentado o seguinte erro:

```
Make package for 2 files.
1/2: 1518-8787-rsp-00007
2/2: 1678-4170-abc-10-01-00010
C:/Markup-91/bin/xml/modules/../../markup/downloaded_markup_journals.csv
[(u'Revista de Sa\xfade P\xfablica', '0034-8910', '1518-8787', '2016nahead'), ('Arquivos Brasileiros de Cardiologia', '0066-782X', '1678-4170', 'v10n1')]
[(u'Revista de Sa\xfade P\xfablica', '0034-8910', '1518-8787', '2016nahead'), ('Arquivos Brasileiros de Cardiologia', '0066-782X', '1678-4170', 'v10n1')]
None
('0034-8910', '1518-8787', u'Revista de Sa\xfade P\xfablica')
('0034-8910', '1518-8787', u'Revista de Sa\xfade P\xfablica')
<modules.article.Journal object at 0x000000000AC6E0F0>
[]
analyze_registered_articles
[None, None, None]
-
analyze_registered_articles
[None, None, None]
-
Validate package (2 files)
Validate 1518-8787-rsp-00007
 - validate journal data
 - validate issue data
 - validate XML structure
Error
  java.net.MalformedURLException: unknown protocol: c
Transformation failed: Run-time errors were reported
 - validate XML contents
Validate 1678-4170-abc-10-01-00010
 - validate journal data
 - validate issue data
 - validate XML structure
Error
  java.net.MalformedURLException: unknown protocol: c
Transformation failed: Run-time errors were reported
 - validate XML contents
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "C:\Markup-91\bin\xml\modules\xml_gui.py", line 113, in run_xml_package_maker
    xml_package_maker(self.selected_folder, pmc)
  File "C:\Markup-91\bin\xml\modules\xml_gui.py", line 149, in xml_package_maker
    xpmaker.make_packages(path, None, pmc=pmc)
  File "C:\Markup-91\bin\xml\modules\xpmaker.py", line 1296, in make_packages
    pack_and_validate(xml_files, results_path, acron, version, is_db_generation)
  File "C:\Markup-91\bin\xml\modules\xpmaker.py", line 1226, in pack_and_validate
    reports.save_report(pkg_maker.report_path, 'xpm.html', _('XML Package Maker Report'))
  File "C:\Markup-91\bin\xml\modules\pkg_validations.py", line 1275, in save_report
    print('Saved report: {f}'.format(f=filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 55: ordinal not in range(128)
```
![pasta-acentuada-xpm](https://cloud.githubusercontent.com/assets/4397365/19437398/0482f35a-9454-11e6-8e60-f5e77cb06b97.jpg)

A pasta "pmc_package" fica vazia.
Porém ao validar a pasta com a nomeação "Teste-xpm" o programa valida corretamente e gera o pacote pmc_package.

**Comment by leticiaquino** [comment]
pasta gerada enviada por e-mail

**Comment by leticiaquino** [comment]
@robertatakenaka 

Ainda apresenta erro:

```code
Make package for 3 files.
1/3: 1414-431X-bjmbr-1414-431X20165340
2/3: 1414-431X-bjmbr-1414-431X20165311
3/3: 1414-431X-bjmbr-1414-431X20164897
C:/Markup-91/bin/xml/modules/../../markup/downloaded_markup_journals.csv
[('Brazilian Journal of Medical and Biological Research', None, '1414-431X', 'v49n10'), ('Brazilian Journal of Medical and Biological Research', None, '1414-431X', 'v49n10'), ('Brazilian Journal of Medical and Biological Research', None, '1414-431X', 'v49n10')]
[('Brazilian Journal of Medical and Biological Research', None, '1414-431X', 'v49n10')]
None
(None, '1414-431X', 'Brazilian Journal of Medical and Biological Research')
(None, '1414-431X', 'Brazilian Journal of Medical and Biological Research')
<modules.article.Journal object at 0x00000000056D72E8>
[]
analyze_registered_articles
[None, None, None]
-
analyze_registered_articles
[None, None, None]
-
analyze_registered_articles
[None, None, None]
-
Validate package (3 files)
Validate 1414-431X-bjmbr-1414-431X20164897
 - validate journal data
 - validate issue data
 - validate XML structure
Error
  java.net.MalformedURLException: unknown protocol: c
Transformation failed: Run-time errors were reported
 - validate XML contents
Validate 1414-431X-bjmbr-1414-431X20165311
 - validate journal data
 - validate issue data
 - validate XML structure
Error
  java.net.MalformedURLException: unknown protocol: c
Transformation failed: Run-time errors were reported
 - validate XML contents
Validate 1414-431X-bjmbr-1414-431X20165340
 - validate journal data
 - validate issue data
 - validate XML structure
Error
  java.net.MalformedURLException: unknown protocol: c
Transformation failed: Run-time errors were reported
 - validate XML contents
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "C:\Markup-91\bin\xml\modules\xml_gui.py", line 113, in run_xml_package_maker
    xml_package_maker(self.selected_folder, pmc)
  File "C:\Markup-91\bin\xml\modules\xml_gui.py", line 149, in xml_package_maker
    xpmaker.make_packages(path, None, pmc=pmc)
  File "C:\Markup-91\bin\xml\modules\xpmaker.py", line 1296, in make_packages
    pack_and_validate(xml_files, results_path, acron, version, is_db_generation)
  File "C:\Markup-91\bin\xml\modules\xpmaker.py", line 1226, in pack_and_validate
    reports.save_report(pkg_maker.report_path, 'xpm.html', _('XML Package Maker Report'))
  File "C:\Markup-91\bin\xml\modules\pkg_validations.py", line 1275, in save_report
    print('Saved report: {f}'.format(f=filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 49: ordinal not in range(128)
```
