### ISSUE TITLE
[xc] Quando o pacote é inválido, levanta uma exceção antes que poder tratá-la

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3211]
### Descrição do problema
Descreva de forma clara e objetiva o problema relatado.

### Passos para reproduzir o problema

1. Executar `scieloxc <path de uma pasta sem arquivos xml>`

```
Traceback (most recent call last):
  File "/home/scielo/xc/app/xc20200602/.xc2020/bin/scieloxcserver", line 11, in <module>
    sys.exit(main())
  File "/home/scielo/xc/app/xc20200602/.xc2020/lib/python3.6/site-packages/prodtools/xc_server.py", line 38, in main
    reception.receive_package()
  File "/home/scielo/xc/app/xc20200602/.xc2020/lib/python3.6/site-packages/prodtools/xc.py", line 94, in receive_package
    return self._receive_package_for_server()
  File "/home/scielo/xc/app/xc20200602/.xc2020/lib/python3.6/site-packages/prodtools/xc.py", line 117, in _receive_package_for_server
    self.convert_package(package_path)
  File "/home/scielo/xc/app/xc20200602/.xc2020/lib/python3.6/site-packages/prodtools/xc.py", line 143, in convert_package
    pkg = pkg_maker.pack()
  File "/home/scielo/xc/app/xc20200602/.xc2020/lib/python3.6/site-packages/prodtools/processing/sps_pkgmaker.py", line 411, in pack
    percent = len(_xml_names) / len(self.source_folder.pkgfiles_items)
ZeroDivisionError: division by zero
```

### Comportamento esperado
O programa deveria informar que o pacote era inválido

### Screenshots ou vídeos
n/a

### Anexos
n/a

### Ambiente utilizado

n/a

**Comment by robertatakenaka** [comment]
relacionado com #3229
