### ISSUE TITLE
[dsteste][xc] Analisar a causa da exceção 'ascii' codec can't encode character '\xf3'

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3277]
### Descrição da tarefa

```
Traceback (most recent call last):
  File "/home/scielo/xc/app/xc_2020/xml/.venv/src/scielo-production-tools/src/scielo/bin/xml/prodtools/xc.py", line 163, in convert_package
    scilista_items, xc_status, mail_info = self.proc.convert_package(package)
  File "/home/scielo/xc/app/xc_2020/xml/.venv/src/scielo-production-tools/src/scielo/bin/xml/prodtools/processing/pkg_processors.py", line 433, in convert_package
    reports = self.report_result(pkg, pkg_eval_result, conversion)
  File "/home/scielo/xc/app/xc_2020/xml/.venv/src/scielo-production-tools/src/scielo/bin/xml/prodtools/processing/pkg_processors.py", line 448, in report_result
    reports.save_report(self.INTERATIVE)
  File "/home/scielo/xc/app/xc_2020/xml/.venv/src/scielo-production-tools/src/scielo/bin/xml/prodtools/validations/reports_maker.py", line 160, in save_report
    encoding.display_message(msg)
  File "/home/scielo/xc/app/xc_2020/xml/.venv/src/scielo-production-tools/src/scielo/bin/xml/prodtools/utils/encoding.py", line 59, in display_message
    print(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 5: ordinal not in range(128)
```

Está ocorrendo com vários pacotes:
- 1516-4446-rbp-nahead-2020.zip
- 1678-9849-rsbmt-v53-Lote 2720-PC.zip
- 1980-5497-rbepid-rpass-0120-23-s1.zip
- 0001-3765-aabc-92-s1-05.zip
- talvez outros mais

O caracter `\xf3` é o `ó` de `Relatório` que é um termo traduzido de `msg = _('Saved report: {f}').format(f=self.report_location)`.

**Comment by robertatakenaka** [comment]
Ao invés de atribuir `LANG=pt` no crontab, atribuir `LANG=pt_BR.UTF-8`.

**Comment by patymori** [comment]
Este problema ocorreu por conta do locale `pt_BR.UTF-8` não estar instalado na máquina onde o erro aconteceu (dsteste). Com a instalação e configuração do locale, o XC funcionou corretamente.
